#undef TAPPING_TERM
#define TAPPING_TERM 180

#define COMBO_TERM 35

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "YlVyb/ZPPoMe"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 8

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

